services:
  db:
    image: pgvector/pgvector:pg17-trixie
    environment:
      - POSTGRES_USER=antifraud_user
      - POSTGRES_PASSWORD=antifraud_pass
      - POSTGRES_DB=antifraud_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U antifraud_user -d antifraud_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
